# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72ea5535962220e232df528452d36b33889296f6135683b07654da2e8a579d8051deb8dbf27aa12439cad1a5d0a9617adb460b27006bf655483de1221b8d3be7

test:
  secret_key_base: b2017eee27873b8d6165600f448fb3043ded87e3e20dad3032e1b9c246bf1288e35ee62799b019116e1df7e780fcf8acf0230dc80a2e6b2c0efc806e4eb932ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
